
function albums(){return shell('Discography','Albums',`<article class="album"><div><img src="${ASSETS.smoke}" alt="Smoke Swig Swear album artwork"></div><div><div class="meta">Studio album · 2013</div><h2>Smoke Swig Swear</h2><div class="detail"><span class="meta">Recorded</span><span>Sound and Motion Studios, Cape Town — four days, September 2012</span></div><div class="detail"><span class="meta">Release</span><span>1 January 2013 · Beast</span></div>${albumLinks('Smoke Swig Swear')}${trackList('smoke')}<p class="bodycopy">BEAST's debut album, recorded in Cape Town and officially launched at The Assembly on 23 February 2013.</p></div></article><article class="album"><div><img src="${ASSETS.bardo}" alt="Bardo album artwork"></div><div><div class="meta">Studio album · 2015</div><h2>Bardo</h2><div class="detail"><span class="meta">Recorded</span><span>Heritage Sound, Cape Town — October 2014, produced by Brendyn Rossouw</span></div><div class="detail"><span class="meta">Release</span><span>6 February 2015 · Beast</span></div>${albumLinks('Bardo')}${trackList('bardo')}<p class="bodycopy">The second BEAST album, themed around the state between life and death and launched at The Assembly in Cape Town on 27 February 2015.</p></div></article><div class="eyebrow">Videography</div><div class="video-list">${[['01','Fill The Hole','Vimeo · 2012','https://vimeo.com'],['02','BEAST Documentary','Vimeo · 2013','https://vimeo.com'],['03','Smoke Swig Swear','Vimeo · 2013','https://vimeo.com'],['04','Wrong Side','YouTube · 2014','https://www.youtube.com']].map(v=>`<a class="video-row" target="_blank" href="${v[3]}"><span>${v[0]}</span><span class="video-title"><strong>${v[1]}</strong><span class="meta">${v[2]}</span></span></a>`).join('')}</div>`)}
function lyricsPage(){return shell('Words, album by album','Lyrics',`<div class="tabs"><button class="pill active" data-album="smoke">Smoke Swig Swear · 2013</button><button class="pill" data-album="bardo">Bardo · 2015</button></div><div id="lyrics-list"></div>`)}
async function renderLyrics(k='smoke'){
 const e=document.querySelector('#lyrics-list');if(!e)return;
 const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 e.innerHTML='<div class="meta" style="padding:24px 0">Loading lyrics…</div>';
 try{
  const r=await fetch('/api/content?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Could not load lyrics');
  const content=await r.json();const album=(content.albums||[]).find(a=>a.key===k);if(!album)throw new Error('Album not found');
  e.innerHTML=`<div class="lyrics-simple">${(album.tracks||[]).map((t,i)=>{const lyrics=String(t.lyrics||'').trim();return lyrics?`<details class="lyric-dropdown" style="border-bottom:1px solid rgba(0,0,0,.18);padding:0"><summary style="list-style:none;cursor:pointer;display:grid;grid-template-columns:52px 1fr auto;gap:14px;align-items:center;padding:20px 0"><span>${String(i+1).padStart(2,'0')}</span><strong>${escapeHtml(t.title)}</strong><span class="meta">Read lyrics +</span></summary><div class="bodycopy" style="white-space:pre-wrap;padding:0 0 28px 66px;max-width:760px;line-height:1.65">${escapeHtml(lyrics)}</div></details>`:`<div class="lyric-name"><span>${String(i+1).padStart(2,'0')}</span><strong>${escapeHtml(t.title)}</strong></div>`}).join('')}</div>`;
 }catch(err){const a=albumsData[k];e.innerHTML=`<div class="lyrics-simple">${a.tracks.map((t,i)=>`<div class="lyric-name"><span>${String(i+1).padStart(2,'0')}</span><strong>${escapeHtml(t[0])}</strong></div>`).join('')}</div>`}
}
function showsPage(){return `<main class="main"><section class="page"><div class="wrap"><div class="eyebrow">Live & festival history</div><div class="show-hero"><img src="${ASSETS.shows}" alt="BEAST performing live under stage lights"></div>${shows.map((s,i)=>`<article class="show"><div><div class="meta">${s[0]}</div><div style="margin-top:8px">${s[1]}</div></div><div><strong>${s[2]}</strong><h2>${s[3]}</h2><p class="bodycopy">${s[4]}</p>${s[5]?`<a class="text-link archive-source" target="_blank" rel="noreferrer" href="${s[5]}">Source ↗</a>`:''}</div><div class="meta">Show ${String(i+1).padStart(2,'0')} / ${String(shows.length).padStart(2,'0')}</div></article>`).join('')}<div class="twocol"><div class="box"><div class="eyebrow">Booking</div><h2>Future dates</h2></div><div class="box"><p class="bodycopy">For future bookings, festival slots and press enquiries, head to the <a class="text-link" href="#/contact">contact page</a> or email bookings@beastband.co.za.</p></div></div></div></section></main>`}