;
const socials=[['Facebook','@BEASTBAND','https://www.facebook.com/BEASTBAND'],['Instagram','@beastbandsa','https://www.instagram.com/beastbandsa'],['YouTube','BEAST','https://www.youtube.com'],['Vimeo','BEAST','https://vimeo.com'],['Spotify','BEAST','https://open.spotify.com']];
const members=[
['Inge Beckmann','Vocals · 2012–present','Also of Lark',"Frontwoman of Cape Town art-rock outfit Lark before its semi-permanent hiatus. Joined BEAST once the two-bass experiment 'sounded right', bringing a method-singing approach that swings between a whisper and a howl. She pushed for a name with an 'interesting visual effect' — Bow Beast — before the band settled on BEAST."],
['Rian Zietsman','Bass guitar · 2011–present','Also of Taxi Violence',"Guitarist of Taxi Violence who bought a bass with Louis Nel in late 2011 purely to learn the instrument. Plays the low, rhythmic end of the twin-bass setup, holding the floor while the second bass climbs over it."],
['Louis Nel','Bass guitar · 2011–present','Also of Taxi Violence',"Taxi Violence's drummer, turned bassist. Runs a higher, chord-based lead approach through a guitar amp — the reason BEAST sounds rawer and more low-fi than a standard rock four-piece."],
['Werner von Waltsleben','Drums · 2013–present','Also of Kobus!',"Drummer of Afrikaans metal band Kobus!. A long-time fan of both Taxi Violence and Lark, he called joining BEAST 'a dream come true' — a chance to play the music he wanted to hear."]];
const timeline=[
['2011','The two-bass experiment begins',"Rian Zietsman and Louis Nel buy bass guitars and begin jamming in the basement of the house they share. Sasha Righini joins on drums and the project develops from an experiment into a band.",'https://www.vice.com/en/article/premiere-watch-beasts-video-for-smoke-swig-swear/'],
['2012','Kombass becomes BEAST',"The early working name Kombass gives way to BEAST after Inge Beckmann joins on vocals. The stripped setup is fixed: two bass guitars, drums and voice.",'https://www.vice.com/en/article/premiere-watch-beasts-video-for-smoke-swig-swear/'],
['2012','First Cape Town shows',"By May 2012 BEAST are being billed at The Assembly in Cape Town as a new supergroup featuring members of Lark, Taxi Violence and The Plastics.",'https://www.bizcommunity.com/Article/196/429/74755.html'],
['2012','Oppikoppi Sweet Thing',"BEAST join the 9–11 August Oppikoppi bill in Northam. Contemporary festival coverage later lists the band among the weekend highlights.",'https://www.news24.com/oppikoppi-2012-crazy-filthy-sweet-fun-20120820'],
['2012','Smoke Swig Swear recorded',"The debut album is recorded over four days in September at Sound and Motion Studios in Cape Town, keeping the twin-bass sound raw and direct.",'https://www.vice.com/en/article/premiere-watch-beasts-video-for-smoke-swig-swear/'],
['2012','Rocking the Daisies',"BEAST play the sold-out Rocking the Daisies festival at Cloof Wine Estate in Darling during the 4–7 October weekend.",'https://lauramccullagh.com/blog/tag/the-brother-moves-on/'],
['2012','Synergy Live',"On 30 November BEAST play the main stage at Synergy Live at Theewaterskloof, scheduled 21:00–21:45 immediately before The Narrow and headliner The Prodigy.",'https://www.last.fm/festival/3408956%2BSynergy%2BLive%2B2012'],
['2013','Up the Creek',"On 1 February BEAST appear on Up the Creek's Friday-night Tribute to Women main-stage programme alongside SAARKIE, Tailor, Machineri and Karen Zoid.",'https://www.news24.com/channel/music/features/up-the-creek-all-you-need-to-know-20130116'],
['2013','Smoke Swig Swear launches',"The debut gets its official album launch at The Assembly in Cape Town on 23 February.",'https://en.wikipedia.org/wiki/Beast_%28South_African_band%29'],
['2013','Design Indaba Music Circuit',"Four days after the album launch, BEAST play the Design Indaba Music Circuit at Aces n Spades as part of a three-day Cape Town programme spanning 32 artists and eight venues.",'https://www.designindaba.com/articles/design-indaba-news/raucous-rock-aces-n-spades'],
['2013','RAMfest',"BEAST are billed for RAMfest Cape Town, 7–10 March at Circle of Dreams near Riviersonderend, on a bill with Rise Against, Bring Me The Horizon and Pendulum.",'https://www.thegremlin.co.za/2013/02/25/sa-bands-have-some-surprises-up-their-sleeves-for-ramfest-2013/'],
['2013','The documentary and international press',"A short documentary follows the album launch, and on 28 August VICE/Noisey premieres the Smoke Swig Swear video alongside an interview with Inge Beckmann and the band's story.",'https://www.vice.com/en/article/premiere-watch-beasts-video-for-smoke-swig-swear/'],
['2013','Line-up change',"Sasha Righini leaves to pursue his own music and Werner von Waltsleben of Kobus! takes over on drums.",'https://en.wikipedia.org/wiki/Beast_%28South_African_band%29'],
['2014','Crowdfunding Bardo',"On 13 August BEAST launch an Indiegogo campaign to fund album two while remaining unsigned and protecting their creative independence. A private investor later helps complete the record.",'https://en.wikipedia.org/wiki/Beast_%28South_African_band%29'],
['2015','Private Bardo acoustic launch',"On 21 February, backers, family and friends attend an intimate acoustic launch at the Cape Town Club, with the material rearranged for a quieter setting.",'https://lauramccullagh.com/blog/2015/02/beast-bardo-exclusive-acoustic-launch-at-the-cape-town-club/'],
['2015','Bardo launches publicly',"The second album receives its public launch on 27 February. Contemporary listings describe the record as the result of the band's 2014 fan-funded recording push.",'https://www.webtickets.co.za/v2/event.aspx?itemid=1447793371'],
['2015','Splashy Fen',"BEAST are announced for Splashy Fen's 2–6 April Easter-weekend edition near Underberg, joining a broad South African bill including Taxi Violence, Shortstraw, aKING and Nakhane Toure.",'https://www.citizen.co.za/highway-mail/uncategorized/2015/02/24/sas-hottest-acts-to-perform-at-splashy-fen/'],
['2015','Critical peak for Bardo',"On 9 April the Mail & Guardian asks whether BEAST might be South Africa's finest live rock act, praising the force of the two-bass setup and Inge Beckmann's vocal range.",'https://mg.co.za/friday/2015-04-09-could-this-be-sa-s-finest-live-rock-act/']
];