;
const lyricNotes={
 'Walls':{excerpt:'Walls in my head vibrate when I drill holes',source:'Kurt Writes Things',url:'https://www.kurtwritesthings.com/things/2013/08/the-beast-with-two-bassists-smoke-swig-swear-album-review'},
 'Healer':{excerpt:'Are you witch, or are you a healer?',source:'Mail & Guardian',url:'https://mg.co.za/friday/2015-04-09-could-this-be-sa-s-finest-live-rock-act/'},
 'Vesica Piscis':{excerpt:'the sum of two parts',source:'Mail & Guardian',url:'https://mg.co.za/friday/2015-04-09-could-this-be-sa-s-finest-live-rock-act/'},
 'Wrong Side':{excerpt:"I'm on the wrong side of the road",source:'The Fuss',url:'https://thefuss.co.za/beast-bardo/'}
};
function header(){return `<header class="header"><div class="wrap header-in"><a class="logo" href="#/">Beast</a><button class="menu">Menu</button><nav class="nav">${['Band','Timeline','Albums','Lyrics','Shows','News','Gallery','Submit','Contact'].map(x=>`<a href="#/${x.toLowerCase()}">${x}</a>`).join('')}</nav></div></header>`}
function footer(){return `<footer class="footer"><div class="wrap footer-in"><div class="foot-brand"><strong>Beast</strong><span>Cape Town, South Africa</span><span>Est. 2012 — Psychological rock and roll</span><a href="#/admin">Band login</a></div><div class="foot-links">${socials.map(s=>`<a target="_blank" rel="noreferrer" href="${s[2]}">${s[0]}</a>`).join('')}</div></div></footer>`}
function shell(eyebrow,title,html){return `<main class="main"><section class="page"><div class="wrap"><div class="eyebrow">${eyebrow}</div><h1 class="title">${title}</h1>${html}</div></section></main>`}
function home(){return `<main class="main home-main"><section class="home-hero"><img src="${ASSETS.hero}" alt="BEAST band"><div class="home-hero-shade"></div><div class="home-hero-content wrap"><div class="eyebrow home-hero-kicker">Cape Town · South Africa · Est. 2012</div><div class="home-hero-foot"><p>Psychological rock and roll built on two bass guitars, drums and one unmistakable voice.</p><a class="hero-cta" href="#/albums">Listen / Explore →</a></div></div></section><section class="home-after"><div class="wrap"><div class="home-intro"><div><div class="eyebrow">The band</div><h2 class="home-section-title">Two basses.<br>Drums. Voice.</h2></div><div><p class="home-lede">BEAST came out of Cape Town in 2012 with a deliberately unusual setup: two bass guitars, drums and Inge Beckmann's voice. Heavy, raw and stripped of the usual lead-guitar architecture.</p><a class="text-link" href="#/band">Read the band story</a></div></div><div class="lineup home-lineup"><div class="eyebrow">Line-up</div>${members.map((m,i)=>`<div class="lineup-row"><span>0${i+1}</span><strong>${m[0]}</strong><span class="meta">${m[1]} — ${m[2].replace('Also of ','ex ')}</span></div>`).join('')}</div><div class="tiles home-tiles">${[['01','Albums','Smoke Swig Swear and Bardo.','albums'],['02','Timeline','From basement sessions to Bardo.','timeline'],['03','Shows','Launches, festivals and live history.','shows'],['04','News','Latest updates and press archive.','news'],['05','Gallery','The complete visual archive.','gallery']].map(t=>`<a class="tile" href="#/${t[3]}"><span class="n">${t[0]}</span><div><h3>${t[1]}</h3><p>${t[2]}</p></div></a>`).join('')}</div><section class="news-home"><div><div class="eyebrow">Latest update</div></div><div class="news-list">${news.slice(0,3).map(n=>`<article><div class="meta">${n[0]} — ${n[1]}</div><h3>${n[2]}</h3><p>${n[3]}</p></article>`).join('')}<div style="padding-top:17px"><a class="text-link" href="#/news">All latest updates and press</a></div></div></section><section class="follow"><div><div class="eyebrow">Follow us</div><h2 style="font-size:44px;letter-spacing:-.05em;margin:0">Stay close</h2></div><div class="socials">${socials.map(s=>`<a target="_blank" rel="noreferrer" href="${s[2]}"><span>${s[0]}</span><span>${s[1]}</span></a>`).join('')}</div></section></div></section></main>`}
function band(){return shell('Bios','The Band',`<div class="band-film" style="position:relative;width:100%;aspect-ratio:16/9;margin:0 0 48px;background:#000;overflow:hidden"><iframe src="https://player.vimeo.com/video/61109646?title=0&byline=0&portrait=0" title="BEAST Documentary" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;inset:0;width:100%;height:100%;border:0"></iframe></div><div class="section-grid">${members.map((m,i)=>`<article class="member"><span>0${i+1}</span><div><h2>${m[0]}</h2><div class="meta">${m[1]}</div><div class="meta" style="margin-top:7px">${m[2]}</div><p>${m[3]}</p></div></article>`).join('')}</div><div class="twocol"><div class="box"><div class="eyebrow">Past members</div><h2>Sasha Righini</h2><div class="meta">Drums · 2011–2013</div><p class="bodycopy">Drummer of The Plastics, invited into the basement sessions early and soon a full member. Left in mid-2013 to pursue his own music.</p></div><div class="box"><div class="eyebrow">Instrumentation</div><p class="bodycopy" style="font-size:20px">The twin-bass setup is rare in South African music. Zietsman plays low and rhythmic like a normal bassist; Nel plays higher and chord-based like a lead guitarist, through a guitar amp. The result is rawer, harder and more low-fi than a standard four-piece.</p></div></div>`)}
function timelinePage(){let last='';const cards=timeline.map((t,i)=>{const y=(t[0].match(/20\d{2}/)||['ARCHIVE'])[0],breakYear=y!==last;last=y;return `${breakYear?`<div class="tl-year-break"><span>${y}</span><i></i></div>`:''}<article class="tl-card"><div class="tl-index">${String(i+1).padStart(2,'0')}</div><div class="tl-date">${t[0]}</div><div class="tl-event"><h2>${t[1]}</h2><p>${t[2]}</p>${t[3]?`<a class="tl-source" target="_blank" rel="noreferrer" href="${t[3]}">VIEW SOURCE ↗</a>`:`<span class="tl-source tl-poster">POSTER / ARCHIVE CONFIRMED</span>`}</div></article>`}).join('');return shell('BEAST LIVE ARCHIVE / 2011 — PRESENT','Timeline',`<section class="tl-intro"><div><strong>${timeline.length}</strong><span>ARCHIVE ENTRIES</span></div><p>Basements, album launches, festivals, clubs and the road between them. A growing chronology reconstructed from surviving posters, contemporary press, ticket archives and live documentation.</p></section><div class="tl-key"><span><b></b> ONLINE SOURCE</span><span><b class="poster-dot"></b> POSTER / ARCHIVE</span></div><div class="timeline-v2">${cards}</div><div class="tl-end"><span>2011 → NOW</span><h2>STILL LOUD.<br>STILL TWO BASSES.</h2><p>This archive is ongoing. Have a flyer, ticket stub, photograph, set list or forgotten date?</p><a href="#/submit">ADD TO THE ARCHIVE ↗</a></div>`)}
function trackList(key){const a=albumsData[key];return `<div class="tracklist">${a.tracks.map((t,i)=>`<div class="trackline"><span>${String(i+1).padStart(2,'0')}</span><strong>${t[0]}</strong><span class="meta">${t[1]}</span></div>`).join('')}<div class="track-summary meta">${a.tracks.length} songs · ${a.total}</div></div>`}
function albumLinks(title){const q=encodeURIComponent('BEAST Cape Town '+title);return `<div class="album-links"><a target="_blank" rel="noreferrer" href="https://open.spotify.com/artist/0355ramjcZBiDQzz1hWSOI">Spotify</a><a target="_blank" rel="noreferrer" href="https://www.youtube.com/results?search_query=${q}">YouTube</a></div>`}