
const shows=[
['2012','May 2012','The Assembly, Cape Town','Early Assembly performance','One of the earliest documented Cape Town listings for BEAST, billed as a new supergroup built from members of Lark, Taxi Violence and The Plastics.','https://www.bizcommunity.com/Article/196/429/74755.html'],
['2012','9–11 Aug 2012','Oppikoppi Farm, Northam, Limpopo','Oppikoppi Sweet Thing','BEAST played Oppikoppi 18 Sweet Thing; contemporary post-festival coverage singled the band out as one of the weekend highlights.','https://www.news24.com/oppikoppi-2012-crazy-filthy-sweet-fun-20120820'],
['2012','4–7 Oct 2012','Cloof Wine Estate, Darling, Western Cape','Rocking the Daisies','BEAST appeared at the 2012 Rocking the Daisies festival during its sold-out Western Cape run.','https://www.concertarchives.org/bands/desmond-and-the-tutus'],
['2012','30 Nov–2 Dec 2012','Theewaterskloof Sports Club, Villiersdorp','Synergy Live Festival','BEAST joined the national-heavy Synergy Live bill headlined by The Prodigy, alongside Jack Parow, Prime Circle, Van Coke Kartel, The Narrow and many more.','https://www.concertarchives.org/bands/the-prodigy?year=2012'],
['2013','1 Feb 2013','Breede River, Swellendam, Western Cape','Up the Creek','BEAST were among the announced South African acts for Up the Creek 2013, alongside Karen Zoid, ISO, YOAV, Jeremy Loops and others.','https://www.timeslive.co.za/tshisa-live/tshisa-live/2012-10-16-up-the-creek-2013/'],
['2013','23 Feb 2013','The Assembly, Cape Town','Smoke Swig Swear album launch','Official Cape Town launch for the debut album Smoke Swig Swear.','https://gevaaalik.com/beast-smoke-swig-swear'],
['2013','27 Feb 2013','Aces n Spades, Cape Town','Design Indaba Music Circuit','BEAST played at 23:30 after The Dollfins and Taxi Violence on the opening night of Design Indaba Music Circuit 2013.','https://mg.co.za/2013-02-22-design-indaba-expo/'],
['2013','7–10 Mar 2013','Circle of Dreams, Riviersonderend, Western Cape','RAMfest Cape Town','BEAST appeared at the Cape Town leg of RAMfest 2013, part of the festival edition headlined by Rise Against, Bring Me The Horizon and Pendulum.','https://en.wikipedia.org/wiki/RAMFest'],
['2013','15–16 Mar 2013','Riversands Farm, Johannesburg, Gauteng','RAMfest Johannesburg','BEAST were also on the Johannesburg RAMfest bill at Riversands Farm, extending the 2013 festival run into Gauteng.','https://www.concertarchives.org/bands/fuzigish?date=past'],
['2015','21 Feb 2015','Cape Town Club, Cape Town','Bardo private acoustic launch','A private acoustic performance for album backers, family and friends, radically reworking BEAST material for the room.','https://lauramccullagh.com/blog/2015/02/beast-bardo-exclusive-acoustic-launch-at-the-cape-town-club/'],
['2015','27 Feb 2015','Cape Town','Bardo album launch','Public launch period for BEAST’s second album Bardo following its crowdfunding and recording campaign.','https://www.webtickets.co.za/v2/event.aspx?itemid=1447793371'],
['2015','29 Mar 2015','Fort Schanskop, Voortrekker Monument, Pretoria','Park Acoustics','A documented Pretoria appearance at Park Acoustics. Contemporary coverage places BEAST on the bill directly after Sannie Fox.','https://rwrant.co.za/3rd-edition-of-park-acoustics-for-2015/'],
['2015','2–6 Apr 2015','Underberg, KwaZulu-Natal','Splashy Fen','BEAST joined Splashy Fen over Easter weekend on a national bill featuring Taxi Violence, Matthew Mole, Shortstraw, aKING, Dan Patlansky and many more.','https://www.citizen.co.za/highway-mail/uncategorized/2015/02/24/sas-hottest-acts-to-perform-at-splashy-fen/']
]
const news=[
  ["07 May 2012","News","Beast debut at The Assembly","Bizcommunity — One of the earliest contemporary notices of BEAST documents the Cape Town debut at The Assembly and introduces the original line-up: Louis Nel and Rian Zietsman of Taxi Violence, Sasha Righini of The Plastics and Lark vocalist Inge Beckmann.","One of the earliest contemporary notices of BEAST documents the Cape Town debut at The Assembly and introduces the original line-up: Louis Nel and Rian Zietsman of Taxi Violence, Sasha Righini of The Plastics and Lark vocalist Inge Beckmann. Source: https://www.bizcommunity.com/Article/196/429/74755.html"],
  ["10 Jul 2012","Feature","BEAST: A Band Apart","One Small Seed — An early profile of the newly formed Cape Town project, cited in later band histories as one of the first substantial pieces on BEAST and its unconventional two-bass approach.","An early profile of the newly formed Cape Town project, cited in later band histories as one of the first substantial pieces on BEAST and its unconventional two-bass approach. Source: https://www.onesmallseed.com/"],
  ["22 Jul 2012","Interview / Feature","Inge Beckmann describes BEAST as the polar opposite of Lark","Evan Milton — In a feature on Lark, Beckmann discusses her then-new dual-bass project BEAST, describing it as a local super-project with members of Taxi Violence and The Plastics and as the polar opposite of Lark.","In a feature on Lark, Beckmann discusses her then-new dual-bass project BEAST, describing it as a local super-project with members of Taxi Violence and The Plastics and as the polar opposite of Lark. Source: https://evanmilton.wordpress.com/2012/07/22/lark-inge-beckmann-and-paul-ressel-are-back/"],
  ["05 Feb 2013","Album Review","BEAST — Smoke Swig Swear","Gevaaalik — A contemporary review focuses on what made the debut unusual in South African rock: no guitars, two bassists, drums and a powerful vocalist, praising the simplicity and originality of the resulting sound.","A contemporary review focuses on what made the debut unusual in South African rock: no guitars, two bassists, drums and a powerful vocalist, praising the simplicity and originality of the resulting sound. Source: https://gevaaalik.com/beast-smoke-swig-swear"],
  ["12 Feb 2013","Profile","Beast: no boundaries","Design Indaba — Design Indaba profiles BEAST around its 2013 Music Circuit appearance, highlighting the band's 'no boundaries' ethos and an organic approach designed to leave room for all four musicians to improvise.","Design Indaba profiles BEAST around its 2013 Music Circuit appearance, highlighting the band's 'no boundaries' ethos and an organic approach designed to leave room for all four musicians to improvise. Source: https://www.designindaba.com/tags/beast"],
  ["27 Feb 2013","Live Review","Raucous rock at Aces n Spades","Design Indaba — Design Indaba's report from its Music Circuit describes a packed Aces n Spades and singles BEAST out as the act the crowd had come to see, documenting the band's rapidly growing Cape Town live reputation.","Design Indaba's report from its Music Circuit describes a packed Aces n Spades and singles BEAST out as the act the crowd had come to see, documenting the band's rapidly growing Cape Town live reputation. Source: https://www.designindaba.com/articles/design-indaba-news/raucous-rock-aces-n-spades"],
  ["22 Mar 2013","Video / Feature","The Jack Daniel's Music Reporter featuring Cape Town band BEAST","2oceansvibe — A video feature introduces BEAST to a wider audience through the members' established Cape Town bands, emphasizing the two-bass/no-guitar setup and Beckmann's commanding vocals.","A video feature introduces BEAST to a wider audience through the members' established Cape Town bands, emphasizing the two-bass/no-guitar setup and Beckmann's commanding vocals. Source: https://www.2oceansvibe.com/2013/03/22/the-jack-daniels-music-reporter-featuring-cape-town-band-beast-video/"],
  ["24 Aug 2013","Album Review","The BEAST With Two Bassists — Smoke Swig Swear","Kurt Writes Things — A detailed review reconstructs the band's origin: Rian Zietsman and Louis Nel deciding they both wanted to learn bass, bringing in Sasha Righini, and developing the idea into the dark garage-rock experiment that became BEAST.","A detailed review reconstructs the band's origin: Rian Zietsman and Louis Nel deciding they both wanted to learn bass, bringing in Sasha Righini, and developing the idea into the dark garage-rock experiment that became BEAST. Source: https://www.kurtwritesthings.com/things/2013/08/the-beast-with-two-bassists-smoke-swig-swear-album-review"],
  ["28 Aug 2013","Premiere / Interview","Premiere: Watch BEAST's video for Smoke Swig Swear","VICE / Noisey — VICE premiered the title-track video internationally, interviewed Inge Beckmann and presented a short documentary about BEAST's rehearsals, recording and album launch. The feature describes the band as a two-bassist, no-guitar quartet mixing rock, punk and grunge.","VICE premiered the title-track video internationally, interviewed Inge Beckmann and presented a short documentary about BEAST's rehearsals, recording and album launch. The feature describes the band as a two-bassist, no-guitar quartet mixing rock, punk and grunge. Source: https://www.vice.com/en/article/premiere-watch-beasts-video-for-smoke-swig-swear/"],
  ["21 Feb 2015","Live / Photography","Bardo exclusive acoustic launch at the Cape Town Club","Laura McCullagh — A photo report documents BEAST's intimate acoustic Bardo launch for supporters at the Cape Town Club, noting how the restrained arrangement intensified the band's music and Beckmann's performance.","A photo report documents BEAST's intimate acoustic Bardo launch for supporters at the Cape Town Club, noting how the restrained arrangement intensified the band's music and Beckmann's performance. Source: https://lauramccullagh.com/blog/2015/02/beast-bardo-exclusive-acoustic-launch-at-the-cape-town-club/"],
  ["29 Mar 2015","Live Review","BEAST at Park Acoustics, Pretoria","Running Wolf's Rant — Coverage of Park Acoustics in Pretoria praises BEAST's heavy twin-bass attack, Beckmann's piercing vocals and the drummer's performance, providing a useful record of the band's Gauteng live activity.","Coverage of Park Acoustics in Pretoria praises BEAST's heavy twin-bass attack, Beckmann's piercing vocals and the drummer's performance, providing a useful record of the band's Gauteng live activity. Source: https://rwrant.co.za/3rd-edition-of-park-acoustics-for-2015/"],
  ["09 Apr 2015","Feature / Album Review","Could this be SA's finest live rock act?","Mail & Guardian — A major national feature examines the making of Bardo, BEAST's experimental origins and its formidable live reputation. It explains how Zietsman and Nel began the project in a shared-house basement and discusses Zietsman's role mixing the second album.","A major national feature examines the making of Bardo, BEAST's experimental origins and its formidable live reputation. It explains how Zietsman and Nel began the project in a shared-house basement and discusses Zietsman's role mixing the second album. Source: https://mg.co.za/friday/2015-04-09-could-this-be-sa-s-finest-live-rock-act/"]
]
const albumsData={
 smoke:{title:'Smoke Swig Swear',year:'2013',total:'32:37',tracks:[
  ['Fill the Hole','4:31'],['Airport Deport Abort','3:28'],['Walls','3:51'],['The Grape','4:09'],['Man in Between','4:43'],['Smoke Swig Swear','4:13'],['Cat Lady','3:04'],['Hand of God','4:38']
 ]},
 bardo:{title:'Bardo',year:'2015',total:'30:53',tracks:[
  ['Healer','3:55'],['Alliance','3:07'],['Out Here','3:29'],['Vesica Piscis','4:33'],['Are We Alive?','2:52'],['Wrong Side','2:48'],['Black Hole','3:48'],['Chant','2:25'],['Down','3:56']
 ]}
}